[build]
  publish = "build/client"
  command = "npm run build"

[[redirects]]
  from = "/api/:route"
  to = "{{env:VITE_GAMES_API_ENDPOINT}}/api/:route"
  status = 200
  force = true

[[redirects]]
  from = "/api/:route/*"
  to = "{{env:VITE_GAMES_API_ENDPOINT}}/api/:route/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/ludo-router/*"
  to = "{{env.VITE_GAMES_API_ENDPOINT}}/static/ludo-router/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200